// src/app.jsx
import eu from './assets/eu.jpg'
import Icon from '@mdi/react'
import { mdiGithub, mdiLinkedin, mdiEmail, mdiOpenInNew } from '@mdi/js'
import { useState, useEffect } from 'preact/hooks'
import { Skill } from './components/skill';

export function App() {

  const [skills, setSkills] = useState([]);
  const [projects, setProjects] = useState([]);

  useEffect(() => {
    async function loadSkills() {
      let res = await fetch('https://dcubix.up.railway.app/skills');
      if (res.ok) {
        let data = await res.json();
        setSkills(data);
      }
    }
    async function loadProjects() {
      let res = await fetch('https://dcubix.up.railway.app/projects');
      if (res.ok) {
        let data = await res.json();
        setProjects(data);
      }
    }

    loadProjects();
    loadSkills();
  }, []);

  return (
    <div className="container mx-auto grid grid-cols-12 gap-4  w-full lg:w-3/5">
      <div
        class="col-span-12"
        style="--levitate:5; --br:5px; --bg:var(--background-alt); --p:24px; --mt:38px; --d:flex; --ai:center;"
      >
        <img src={eu} alt="Diego Lopes" style="--w:100px; --h:100px; --br:120px" />
        <div style="--d:flex; --fd:column; --jc:center; --ml:15px">
          <span className="text-2xl font-bold">Diego Lopes</span>
          <span className="text-lg">Software Developer</span>
          <div class="group">
            <a href="#" style="--mr:8px"><Icon path={mdiGithub} size={1.3} /></a>
            <a href="#" style="--mr:8px"><Icon path={mdiLinkedin} size={1.4} /></a>
            <a href="#"><Icon path={mdiEmail} size={1.4} /></a>
          </div>
        </div>
      </div>

      <div
        class="col-span-12 md:col-span-9"
        style="--levitate:5; --br:5px; --bg:var(--background-alt); --p:24px;"
      >
        <span className="text-3xl block" style="margin-bottom: 12px;">Hello!</span>
        <span className="text-lg">
          I like computer graphics, databases and Flutter.
          Professionally, I make mobile and web applications for a dealership company.
          And I occasionally mess with electronics.
          I have been coding for more than 9 years now.
        </span>
      </div>

      <div
        class="col-span-12 md:col-span-3"
        style="--levitate:5; --br:5px; --bg:var(--background-alt); --p:24px"
      >
        <span className="text-3xl block" style="margin-bottom: 12px;">Skills</span>
        <div style="--d:flex; --fw:wrap">
          {skills.map((sk) => <Skill skill={sk}></Skill>)}
        </div>
      </div>

      <div
        class="col-span-12"
        style="--p:24px; --d:flex; --ai:center;"
      >
        <span className="text-3xl block">My Work</span>
      </div>
      
      {
        projects.map((p) => (<div
          class="col-span-6"
          style="--levitate:5; --br:5px; --bg:var(--background-alt); --p:24px;"
        >
          <span className="text-2xl block" style="margin-bottom: 12px;">{p.title}</span>
          <p>{p.description} <a aria-label="More Info" href={p.url}><Icon aria-roledescription="img" path={mdiOpenInNew} size={1} target="_blank" /> More Info</a></p>
          <div style="--d:flex; --fw:wrap; --cg:12px; --mt:12px">
            {p.images.map((im) => <a href={im} target="_blank">
              <div style={{
                backgroundImage: 'url(' + im + ')',
                backgroundPosition: 'center',
                backgroundSize: 'cover',
                width: '160px',
                height: '160px',
                '--br': '6px',
                '--levitate': '5'
              }}></div>
            </a>)}
          </div>
        </div>))
      }
    </div>
  )
}

// src/App.svelte
<script lang="ts">
    import me from './assets/me.jpg';
    import { GithubIcon, LinkedinIcon, MailIcon, LinkIcon } from 'svelte-feather-icons';
    import Card from './lib/components/Card.svelte';
    import { SkillController } from './lib/controller/SkillsController';
    import SkillView from './lib/components/SkillView.svelte';
    import Loader from './lib/components/Loader.svelte';
    import { ProjectController } from './lib/controller/ProjectController';
    import Image from './lib/components/Image.svelte';
</script>

<main>
    <div class="md:w-3/5 md:mx-auto p-4">
        <Card>
            <img src={me} alt="Diego Lopes" class="w-20 h-20 md:w-32 md:h-32 rounded-full drop-shadow-xl" />
            <div class="flex flex-col justify-center ml-6">
                <h4 class="m-0 font-bold tracking-tight text-2xl md:text-4xl">Diego Lopes</h4>
                <h5 class="m-0 mb-2 font-normal md:text-xl">Software Developer</h5>
                <ul class="flex gap-3">
                    <li><a href="https://github.com/DCubix" title="GitHub" target="_blank" class="text-cyan-400 inline-block"><GithubIcon size="24" /></a></li>
                    <li><a href="https://www.linkedin.com/in/diego-lopes-a47056177/" title="LinkedIn" target="_blank" class="text-cyan-400 inline-block"><LinkedinIcon size="24" /></a></li>
                    <li><a href="mailto:diego95lopes@gmail.com" title="E-mail" target="_blank" class="text-cyan-400 inline-block"><MailIcon size="24" /></a></li>
                </ul>
            </div>
        </Card>

        <div class="flex flex-col md:flex-row">
            <Card style="flex-1" title="Hello!">
                <div>
                    <p class="text-justify">
                        I'm a software developer from Brazil that loves to code.
                    </p>
                    <p class="text-justify">
                        I enjoy doing mobile and web dev, but I really have a passion for
                        low level C++ coding coupled with computer graphics. However I do mobile dev and also some web dev for a living.
                    </p>
                </div>
            </Card>
            <Card style="flex-1 md:flex-none md:w-72" title="Skills">
                {#await SkillController.fetch()}
                    <Loader />
                {:then value}
                    <div class="flex flex-wrap">
                        {#each value as skill}
                            <SkillView skill={skill} />
                        {:else}
                            <span class="text-gray-500">No skills found.</span>
                        {/each}
                    </div>
                {:catch error}
                    <span class="text-gray-500">Failed to fetch skills.</span>
                {/await}
            </Card>
        </div>

        <h4 class="mx-8 my-5 font-bold tracking-tight text-2xl md:text-3xl">My Work</h4>

        <div class="grid grid-cols-1 md:grid-cols-2 place-content-center">
            {#await ProjectController.fetch()}
                <Loader />
            {:then value}
                {#each value as project}
                    <Card style="flex-1" title={project.title}>
                        <div class="flex flex-col">
                            <p>
                                {project.description}
                                <a href={project.url} target="_blank" class="text-cyan-400 flex items-center"><LinkIcon size="16" /> More Info</a>
                            </p>
                            <div class="flex flex-row flex-wrap">
                                {#each project.images as image}
                                    <Image src={image} />
                                {/each}
                            </div>
                        </div>
                    </Card>
                {:else}
                    <span class="text-gray-500">No projects found.</span>
                {/each}
            {:catch error}
                <span class="text-gray-500">Failed to fetch projects.</span>
            {/await}
        </div>
    </div>
</main>
